#!/usr/bin/env bash
#
# Yamada Hayao
# Twitter: @Hayao0819
# Email  : hayao@fascode.net
#
# (c) 2019-2020 Fascode Network.
#
# config
#
# Overwrites the first to read and set the build script
# This configuration file follows the bash syntax.
#

# Image file label
iso_label="Madeine_$(date +%Y%m%d)"

# Image file creator information
iso_publisher='Yahada Hayao <https://twitter.com/Hayao0819>'

# Image file name (not file name)
iso_application="AlterLinux Madeleine Live/Rescue CD"

# Set to true to enable plymouth.(-b)
boot_splash=false

# Set the Japanese mode.
# When this is enabled, the packages in the japanese package list will be installed.
# A file for Japanese input is added.
japanese=false
